language: groovy

sudo: false

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.4"

cache:
  directories:
    - ~/.grails

before_script:
  - psql -c 'create database sample;' -U postgres
  - npm install -g bower

script:
  - ./grailsw war
  - ./grailsw codenarc
  - cat static-analysis.txt
