language: groovy
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database sample;' -U postgres

script:
  - ./grailsw compile
  - ./grailsw bootstrap -DnoTomcat=true
