language: groovy

sudo: false

jdk: oraclejdk8

cache:
  directories:
    - ~/.grails

before_script:
  - npm install -g bower eslint@1.0.0-rc-1

script:
  - eslint web-app/js/source
  - ./grailsw war
