language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

sudo: false

before_script:
  - psql -c 'create database sample;' -U postgres

script:
  - ./grailsw compile
  - ./grailsw codenarc
  - cat static-analysis.txt
  - pwd
  - cd ~/
  - pwd
  - ls -lar
