language: groovy

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.4"

sudo: false

before_script:
  - psql -c 'create database sample;' -U postgres

script:
  - ./grailsw refresh-dependencies
  - ./grailsw codenarc
  - cat static-analysis.txt
