language: groovy

sudo: false

jdk: oraclejdk8

cache:
  directories:
    - ~/.grails

before_script:
  - npm install -g bower eslint@next

script:
  - ./grailsw war
  - ./grailsw codenarc
  - cat static-analysis.txt
  - eslint web-app/js/source --inline-config=false
