ruleset {
	description 'IMODS Groovy Styleguide'

	// Basic Rules
	AssertWithinFinallyBlock(priority: 1)
	AssignmentInConditional(priority: 1)
	BigDecimalInstantiation(priority: 1)
	BitwiseOperatorInConditional(priority: 1)
	BooleanGetBoolean(priority: 1)
	BrokenNullCheck(priority: 1)
	BrokenOddnessCheck(priority: 1)
	ClassForName(priority: 1)
	ComparisonOfTwoConstants(priority: 1)
	ComparisonWithSelf(priority: 1)
	ConstantAssertExpression(priority: 1)
	ConstantIfExpression(priority: 1)
	ConstantTernaryExpression(priority: 1)
	DeadCode(priority: 1)
	DoubleNegative(priority: 1)
	DuplicateCaseStatement(priority: 1)
	DuplicateMapKey(priority: 1)
	DuplicateSetValue(priority: 1)
	EmptyCatchBlock(priority: 1)
	EmptyClass(priority: 1)
	EmptyElseBlock(priority: 1)
	EmptyFinallyBlock(priority: 1)
	EmptyForStatement(priority: 1)
	EmptyIfStatement(priority: 1)
	EmptyInstanceInitializer(priority: 1)
	EmptyMethod(priority: 1)
	EmptyStaticInitializer(priority: 1)
	EmptySwitchStatement(priority: 1)
	EmptySynchronizedStatement(priority: 1)
	EmptyTryBlock(priority: 1)
	EmptyWhileStatement(priority: 1)
	EqualsAndHashCode(priority: 1)
	EqualsOverloaded(priority: 1)
	ExplicitGarbageCollection(priority: 1)
	ForLoopShouldBeWhileLoop(priority: 1)
	HardCodedWindowsFileSeparator(priority: 1)
	HardCodedWindowsRootDirectory(priority: 1)
	IntegerGetInteger(priority: 1)
	MultipleUnaryOperators(priority: 1)
	RandomDoubleCoercedToZero(priority: 1)
	RemoveAllOnSelf(priority: 1)
	ReturnFromFinallyBlock(priority: 1)
	ThrowExceptionFromFinallyBlock(priority: 1)

	// Braces Rules
	ElseBlockBraces(priority: 2)
	ForStatementBraces(priority: 2)
	IfStatementBraces(priority: 2)
	WhileStatementBraces(priority: 2)

	// Unnecessary Rules
	AddEmptyString(priority: 2)
	ConsecutiveLiteralAppends(priority: 2)
	ConsecutiveStringConcatenation(priority: 2)
	UnnecessaryBigDecimalInstantiation(priority: 2)
	UnnecessaryBigIntegerInstantiation(priority: 2)
	UnnecessaryBooleanExpression(priority: 2)
	UnnecessaryBooleanInstantiation(priority: 2)
	UnnecessaryCallForLastElement(priority: 2)
	UnnecessaryCallToSubstring(priority: 2)
	UnnecessaryCast(priority: 2)
	UnnecessaryCatchBlock(priority: 2)
	UnnecessaryCollectCall(priority: 2)
	UnnecessaryCollectionCall(priority: 2)
	UnnecessaryConstructor(priority: 1)
	UnnecessaryDefInFieldDeclaration(priority: 2)
	UnnecessaryDefInMethodDeclaration(priority: 2)
	UnnecessaryDefInVariableDeclaration(priority: 2)
	UnnecessaryDotClass(priority: 2)
	UnnecessaryDoubleInstantiation(priority: 2)
	UnnecessaryElseStatement(priority: 1)
	UnnecessaryFinalOnPrivateMethod(priority: 2)
	UnnecessaryFloatInstantiation(priority: 2)
	UnnecessaryGetter(enabled: false)
	UnnecessaryGString(priority: 1)
	UnnecessaryIfStatement(priority: 1)
	UnnecessaryInstanceOfCheck(priority: 2)
	UnnecessaryInstantiationToGetClass(priority: 2)
	UnnecessaryIntegerInstantiation(priority: 2)
	UnnecessaryLongInstantiation(priority: 2)
	UnnecessaryModOne(priority: 2)
	// TODO enable this rule
	UnnecessaryObjectReferences(enabled: false)
	UnnecessaryNullCheck(priority: 2)
	UnnecessaryNullCheckBeforeInstanceOf(priority: 2)
	UnnecessaryOverridingMethod(priority: 2)
	UnnecessaryPackageReference(priority: 2)
	UnnecessaryParenthesesForMethodCallWithClosure(priority: 2)
	UnnecessaryPublicModifier(priority: 2)
	UnnecessaryReturnKeyword(priority: 2)
	UnnecessarySafeNavigationOperator(priority: 2)
	UnnecessarySelfAssignment(priority: 2)
	UnnecessarySemicolon(priority: 1)
	UnnecessarySubstring(priority: 2)
	UnnecessaryStringInstantiation(priority: 2)
	UnnecessaryTernaryExpression(priority: 1)
	UnnecessaryTransientModifier(enabled: false)
	UnnecessaryToString(priority: 2)

	// Unused Rules
	UnusedArray(priority: 1)
	UnusedObject(priority: 1)
	UnusedPrivateField(priority: 1)
	UnusedPrivateMethod(priority: 1)
	UnusedPrivateMethodParameter(priority: 1)
	UnusedMethodParameter(priority: 1)
	UnusedVariable(priority: 1)
}
